import type {
  Booking,
  Profile,
  Rental,
  RentalCar,
  Review,
  Service,
  ServiceCategory,
  Vehicle,
} from '@/types';

export const mockProfile: Profile = {
  id: 'demo-user',
  email: 'demo@autoduck.example',
  fullName: 'Carlos Silva',
  avatarUrl: 'https://i.pravatar.cc/200?img=12',
  phone: '+55 11 99999-0000',
  role: 'client',
  preferredLanguage: 'pt-BR',
  createdAt: new Date().toISOString(),
};

export const mockAdminProfile: Profile = {
  ...mockProfile,
  id: 'demo-admin',
  fullName: 'Ana Souza',
  role: 'admin',
  email: 'admin@autoduck.example',
};

export const mockVehicles: Vehicle[] = [
  {
    id: 'v1',
    ownerId: mockProfile.id,
    make: 'Volkswagen',
    model: 'Polo',
    year: 2021,
    plate: 'ABC-1D23',
    color: 'Silver',
  },
  {
    id: 'v2',
    ownerId: mockProfile.id,
    make: 'Fiat',
    model: 'Pulse',
    year: 2023,
    plate: 'XYZ-4E56',
    color: 'White',
  },
];

export const serviceCategories: ServiceCategory[] = [
  { id: 'c1', type: 'repair', slug: 'engine', nameKey: 'Engine', icon: 'engine' },
  { id: 'c2', type: 'repair', slug: 'brakes', nameKey: 'Brakes', icon: 'brakes' },
  { id: 'c3', type: 'repair', slug: 'suspension', nameKey: 'Suspension', icon: 'suspension' },
  { id: 'c4', type: 'repair', slug: 'electrical', nameKey: 'Electrical', icon: 'bolt' },
  { id: 'c5', type: 'wash', slug: 'basic', nameKey: 'Basic wash', icon: 'wash' },
  { id: 'c6', type: 'wash', slug: 'premium', nameKey: 'Premium wash', icon: 'sparkle' },
];

export const mockServices: Service[] = [
  {
    id: 's1',
    categoryId: 'c1',
    type: 'repair',
    name: 'Engine diagnostics',
    description: 'Full computer diagnostics, error codes and inspection report.',
    priceFrom: 180,
    durationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800',
    rating: 4.8,
    reviewsCount: 124,
  },
  {
    id: 's2',
    categoryId: 'c2',
    type: 'repair',
    name: 'Brake pads replacement',
    description: 'Front or rear pads + brake fluid check.',
    priceFrom: 320,
    durationMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1632823469850-2f77dd1eea7c?w=800',
    rating: 4.9,
    reviewsCount: 88,
  },
  {
    id: 's3',
    categoryId: 'c3',
    type: 'repair',
    name: 'Suspension check',
    description: 'Shock absorbers, springs and bushings inspection.',
    priceFrom: 240,
    durationMinutes: 75,
    imageUrl: 'https://images.unsplash.com/photo-1615906655593-ad0386982a0f?w=800',
    rating: 4.7,
    reviewsCount: 56,
  },
  {
    id: 's4',
    categoryId: 'c4',
    type: 'repair',
    name: 'Battery service',
    description: 'Battery test, charge and replacement.',
    priceFrom: 150,
    durationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=800',
    rating: 4.6,
    reviewsCount: 42,
  },
  {
    id: 's5',
    categoryId: 'c5',
    type: 'wash',
    name: 'Basic wash',
    description: 'Exterior wash, drying and tire shine.',
    priceFrom: 60,
    durationMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1605618826115-fb9e0cabd9c4?w=800',
    rating: 4.5,
    reviewsCount: 211,
  },
  {
    id: 's6',
    categoryId: 'c6',
    type: 'wash',
    name: 'Premium detail',
    description: 'Inside-out detail, wax and leather treatment.',
    priceFrom: 220,
    durationMinutes: 120,
    imageUrl: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=800',
    rating: 4.9,
    reviewsCount: 167,
  },
];

export const mockRentalCars: RentalCar[] = [
  {
    id: 'r1',
    make: 'Chevrolet',
    model: 'Onix',
    year: 2024,
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    pricePerDay: 220,
    depositAmount: 800,
    imageUrl: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=1200',
    available: true,
    rating: 4.7,
    reviewsCount: 64,
    description:
      'Compact and economical hatch, perfect for the city. Air conditioning, low fuel consumption and easy parking.',
  },
  {
    id: 'r2',
    make: 'Volkswagen',
    model: 'T-Cross',
    year: 2023,
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    pricePerDay: 320,
    depositAmount: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200',
    available: true,
    rating: 4.8,
    reviewsCount: 41,
    description:
      'Stylish compact SUV with a roomy trunk and high ground clearance. Great for both city and weekend trips.',
  },
  {
    id: 'r3',
    make: 'Tesla',
    model: 'Model 3',
    year: 2024,
    transmission: 'automatic',
    fuel: 'electric',
    seats: 5,
    pricePerDay: 690,
    depositAmount: 2500,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200',
    available: true,
    rating: 4.9,
    reviewsCount: 87,
    description:
      'Fully electric premium sedan with autopilot, instant acceleration and a long range. Zero emissions.',
  },
  {
    id: 'r4',
    make: 'Toyota',
    model: 'Corolla Cross',
    year: 2023,
    transmission: 'automatic',
    fuel: 'hybrid',
    seats: 5,
    pricePerDay: 410,
    depositAmount: 1500,
    imageUrl: 'https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=1200',
    available: true,
    rating: 4.8,
    reviewsCount: 52,
    description:
      'Hybrid crossover combining low consumption with comfort. Spacious cabin and modern safety features.',
  },
  {
    id: 'r5',
    make: 'Fiat',
    model: 'Mobi',
    year: 2022,
    transmission: 'manual',
    fuel: 'petrol',
    seats: 4,
    pricePerDay: 140,
    depositAmount: 500,
    imageUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=1200',
    available: false,
    rating: 4.4,
    reviewsCount: 31,
    description:
      'Ultra-affordable city car with manual transmission. The cheapest way to get around town.',
  },
];

const now = Date.now();
const inDays = (d: number) => new Date(now + d * 86_400_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    clientId: mockProfile.id,
    serviceId: 's2',
    service: mockServices[1],
    vehicleId: 'v1',
    scheduledAt: inDays(2),
    status: 'confirmed',
    totalAmount: 320,
    createdAt: daysAgo(1),
  },
  {
    id: 'b2',
    clientId: mockProfile.id,
    serviceId: 's5',
    service: mockServices[4],
    vehicleId: 'v2',
    scheduledAt: daysAgo(7),
    status: 'completed',
    totalAmount: 60,
    createdAt: daysAgo(8),
  },
];

export const mockRentals: Rental[] = [
  {
    id: 'rent1',
    clientId: mockProfile.id,
    carId: 'r1',
    car: mockRentalCars[0],
    startDate: inDays(5),
    endDate: inDays(8),
    status: 'confirmed',
    totalAmount: 220 * 3,
    depositAmount: 800,
    createdAt: daysAgo(2),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev1',
    clientId: 'u1',
    clientName: 'Mariana O.',
    serviceId: 's2',
    rating: 5,
    comment: 'Atendimento rápido e impecável. Recomendo!',
    createdAt: daysAgo(3),
  },
  {
    id: 'rev2',
    clientId: 'u2',
    clientName: 'Pedro L.',
    serviceId: 's6',
    rating: 5,
    comment: 'Carro saiu zero! Brasileiríssimo de bom.',
    createdAt: daysAgo(10),
  },
  {
    id: 'rev3',
    clientId: 'u3',
    clientName: 'João F.',
    carId: 'r3',
    rating: 5,
    comment: 'Aluguei a Model 3 — experiência top!',
    createdAt: daysAgo(14),
  },
];
